all:
  children:
    load_balancers:
      hosts:
        load_balancer:
          ansible_host: 57.128.7.101
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    web_servers:
      hosts:
        web_server_1:
          ansible_host: 57.128.7.178
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        web_server_2:
          ansible_host: 57.128.7.123
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    app_servers:
      hosts:
        app_server_1:
          ansible_host: 57.128.7.208
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          db_host: 57.128.7.63
        app_server_2:
          ansible_host: 57.128.7.184
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          db_host: 57.128.7.63

    db_servers:
      hosts:
        db_server_1:
          ansible_host: 57.128.7.63
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          db_role: master
          db_slave_ip: 57.128.7.119
        db_server_2:
          ansible_host: 57.128.7.119
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          db_role: slave
          db_master_ip: 57.128.7.63

  vars:
    web_server_ips:
      - 57.128.7.178
      - 57.128.7.123
    app_server_ips:
      - 57.128.7.208
      - 57.128.7.184
